# Even Fibonacci numbers

# Problem 2

# Each new term in the Fibonacci sequence is generated by adding the previous 
# two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed 
# four million, find the sum of the even-valued terms.

def listFib(n):
	list = [1, 1, 2]
	keepGoing = True
	while keepGoing == True:
		new = list[-1] + list[-2]
		if new > n:
			keepGoing = False
		else:
			list.append(new)
	return list

answer = 0
Fib = listFib(4000000)
for num in Fib:
	if num % 2 == 0:
		answer += num

print(answer)